<?php

/**
 * @file
 * Module file for crosswords.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\crosswords\Controller\CrosswordsController;

/**
 * {@inheritdoc}
 */
function crosswords_theme($existing, $type, $theme, $path) {
  return [
    'crosswords-crosswords' => [
      'variables' => [
        'crosswords_variable_title' => NULL,
      ],
    ],
  ];
}

/**
 * {@inheritdoc}
 */
function crosswords_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $defaultCells = '["","","","",""],["","","","",""],["","","","",""],["","","","",""],["","","","",""]';
  switch ($form_id) {
    case 'node_crosswords_edit_form':
      // Processing Crosswords GRID.
      $savedCrosswords = $form['field_crosswords_text']['widget'][0]['value']['#default_value'];
      if (strpos($savedCrosswords, '###') !== FALSE) {
        $explodedSavedCrosswords = explode('###', $savedCrosswords);
      }
      $crosswordsArray = explode(",", $explodedSavedCrosswords[1]);
      $crosswordsData = '[';
      $counter = 1;
      $arrayCounted = count($crosswordsArray);
      $crosswordsDataTemp = '';
      foreach ($crosswordsArray as $cArrayKey => $cArrayValue) {
        $crosswordsDataTemp = $crosswordsDataTemp ? $crosswordsDataTemp . ',"' . $cArrayValue . '"' : '"' . $cArrayValue . '"';
        if ($counter == $arrayCounted) {
          $crosswordsData .= $crosswordsDataTemp;
        }
        if (($counter % $explodedSavedCrosswords[0] == 0) && ($counter < $arrayCounted)) {
          $crosswordsData .= $crosswordsDataTemp . '],[';
          $crosswordsDataTemp = '';
        }
        $counter++;
      }
      $crosswordsData .= ']';
      $form['#attached']['drupalSettings']['crosswordsData'] = $explodedSavedCrosswords[1] ? $crosswordsData : $defaultCells;
      $horizontal_hint = CrosswordsController::processCrosswordsHints($form['field_crosswords_hrow']['widget'][0]['value']['#default_value']);
      $form['#attached']['drupalSettings']['horizontal_row'] = $horizontal_hint['row'] ? $horizontal_hint['row'] : '';
      $form['#attached']['drupalSettings']['horizontal_col'] = $horizontal_hint['col'] ? $horizontal_hint['col'] : '';
      $form['#attached']['drupalSettings']['horizontal_data'] = $horizontal_hint['data'] ? $horizontal_hint['data'] : '';
      $verticle_hint = CrosswordsController::processCrosswordsHints($form['field_crosswords_hcolumn']['widget'][0]['value']['#default_value']);
      $form['#attached']['drupalSettings']['verticle_row'] = $verticle_hint['row'] ? $verticle_hint['row'] : '';
      $form['#attached']['drupalSettings']['verticle_col'] = $verticle_hint['col'] ? $verticle_hint['col'] : '';
      $form['#attached']['drupalSettings']['verticle_data'] = $verticle_hint['data'] ? $verticle_hint['data'] : '';
      // Load libraries/ themes of this Module and Check if its available to load automatically.
      $form['#attached']['library'][] = 'crosswords/crosswords.addedit';
      $language = $form['language']['#value'];
      $form['field_rows'][$language]['#suffix'] = '<label for="edit-field-crosswords-text-0-value"><b>Set Words</b> (Right Click on the Sheet below to add-remove Row-Column) </label><div id="crosswordsContainerDiv"></div><div id="crosswordsContainerDivRowColumn"></div>';
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          $form['actions'][$action]['#submit'][] = 'crosswords_edit_form_handler';
        }
      }
      
     break;
    case 'node_crosswords_form':
      $form['#attached']['drupalSettings']['crosswordsData'] = $defaultCells;
      $form['#attached']['library'][] = 'crosswords/crosswords.addedit';
      $language = $form['language']['#value'];
      $form['field_rows'][$language]['#suffix'] = '<label for="edit-field-crosswords-text-0-value"><b>Set Words</b> (Right Click on the Sheet below to add-remove Row-Column)</label><div id="crosswordsContainerDiv"></div><div id="crosswordsContainerDivRowColumn"></div>';
     break;
  }
}
