<?php

/**
 * @file
 * Module file for crosswords.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\crosswords\Controller\CrosswordsController;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * {@inheritdoc}
 */
function crosswords_theme($existing, $type, $theme, $path) {
  return [
    'crosswords-crosswords' => [
      'variables' => [
        'crosswords_variable_title' => NULL,
      ],
    ],
  ];
}

/**
 * {@inheritdoc}
 */
function crosswords_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $defaultCells = '["","","","",""],["","","","",""],["","","","",""],["","","","",""],["","","","",""]';
  switch ($form_id) {
    case 'node_crosswords_edit_form':
      // Processing Crosswords GRID.
      $savedCrosswords = $form['field_crosswords_text']['widget'][0]['value']['#default_value'];
      if (strpos($savedCrosswords, '###') !== FALSE) {
        $explodedSavedCrosswords = explode('###', $savedCrosswords);
      }
      $crosswordsArray = explode(",", $explodedSavedCrosswords[1]);
      $crosswordsData = '[';
      $counter = 1;
      $arrayCounted = count($crosswordsArray);
      $crosswordsDataTemp = '';
      foreach ($crosswordsArray as $cArrayValue) {
        $crosswordsDataTemp = $crosswordsDataTemp ? $crosswordsDataTemp . ',"' . $cArrayValue . '"' : '"' . $cArrayValue . '"';
        if ($counter == $arrayCounted) {
          $crosswordsData .= $crosswordsDataTemp;
        }
        if (($counter % $explodedSavedCrosswords[0] == 0) && ($counter < $arrayCounted)) {
          $crosswordsData .= $crosswordsDataTemp . '],[';
          $crosswordsDataTemp = '';
        }
        $counter++;
      }
      $crosswordsData .= ']';
      $form['#attached']['drupalSettings']['crosswordsData'] = $explodedSavedCrosswords[1] ? $crosswordsData : $defaultCells;
      $horizontal_hint = CrosswordsController::processCrosswordsHints($form['field_crosswords_hrow']['widget'][0]['value']['#default_value']);
      $form['#attached']['drupalSettings']['horizontal_row'] = $horizontal_hint['row'] ? $horizontal_hint['row'] : '';
      $form['#attached']['drupalSettings']['horizontal_col'] = $horizontal_hint['col'] ? $horizontal_hint['col'] : '';
      $form['#attached']['drupalSettings']['horizontal_data'] = $horizontal_hint['data'] ? $horizontal_hint['data'] : '';
      $verticle_hint = CrosswordsController::processCrosswordsHints($form['field_crosswords_hcolumn']['widget'][0]['value']['#default_value']);
      $form['#attached']['drupalSettings']['verticle_row'] = $verticle_hint['row'] ? $verticle_hint['row'] : '';
      $form['#attached']['drupalSettings']['verticle_col'] = $verticle_hint['col'] ? $verticle_hint['col'] : '';
      $form['#attached']['drupalSettings']['verticle_data'] = $verticle_hint['data'] ? $verticle_hint['data'] : '';
      // Load libraries/ themes of this Module automatically.
      $form['#attached']['library'][] = 'crosswords/crosswords.addedit';
      $language = $form['language']['#value'];
      $form['field_rows'][$language]['#suffix'] = '<label for="edit-field-crosswords-text-0-value"><b>Set Words in the table Below</b> (Right Click on the Table below to add-remove Row-Column) </label><div id="crosswordsContainerDiv"></div><div id="crosswordsContainerDivRowColumn"></div>';
      foreach (array_keys($form['actions']) as $action) {
        if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
          $form['actions'][$action]['#submit'][] = 'crosswords_edit_form_handler';
        }
      }
      break;

    case 'node_crosswords_form':
      $form['#attached']['drupalSettings']['crosswordsData'] = $defaultCells;
      $form['#attached']['library'][] = 'crosswords/crosswords.addedit';
      $language = $form['language']['#value'];
      $form['field_rows'][$language]['#suffix'] = '<label for="edit-field-crosswords-text-0-value"><b>Set Words in the table Below</b> (Right Click on the Table below to add-remove Row-Column)</label><div id="crosswordsContainerDiv"></div><div id="crosswordsContainerDivRowColumn"></div>';
      break;
  }
}

/**
 * Implements crosswords_help().
 */
function crosswords_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.crosswords':
      $output = '<h2>' . t('Crosswords:') . '</h2>';
      $output .= '<p>' . t('Follow these steps to set up and start using your Crosswords:') . '</p>';
      $output .= '<ol>';
      $output .= '<li>' . t('<strong>Install -</strong> Once this Module is installed Editor can found a new content type as "Crosswords".') . '</li>';
      $output .= '<li>' . t('Now create some crosswords content based on this content type. Lets say, We have created two crosswords content and these are Crosswords1 and Crosswords2.') . '</li>';
      $output .= '<li>' . t('To Display a particular crosswords say Crosswords1 in frontend Editor can set url like "www.myplayground.com/crosswords/1" where 1 is the {nid} of Crosswords1."') . '</li>';
      // Display a link to create content page if Crosswords is enabled.
      if (\Drupal::moduleHandler()->moduleExists('crosswords')) {
        $output .= '<li>' . t('<strong>Start creating Crosswords -</strong> Finally, you may click here <a href=":content/crosswords">add new Crosswords</a>.', [':content' => \Drupal::url('node.add_page')]) . '</li>';
      }
      $output .= '<li>' . t('<strong>Un-Install -</strong> Un-installation automatically deleted the Crosswords contents and content type.') . '</li>';
      $output .= '<li>' . t('Found problem to uninstall crosswords. First un-install the Module then delete contents and content type recursively.') . '</li>';
      $output .= '<li>' . t('As Crosswords Module contains Locked Content type Admin need to un-install Module first.') . '</li>';
      $output .= '<li>' . t('<strong>Re-Install -</strong> Please delete all crosswords contents and crosswords content type first.') . '</li>';
      $output .= '</ol>';
      return ['#markup' => $output];
  }
}
