<?php

/**
 * {@inheritdoc}
 */
function geoip_content_page_attachments(array &$attachments) {
  $attachments['#attached']['drupalSettings']['geoipCountry'] = get_countryCode_by_geoip();
  $attachments['#attached']['library'][] = 'geoip_content/geoip_content';
}

/**
 * {@inheritdoc}
 */
function geoip_content_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\Sql $query) {
  switch ($view->id()) {
    case 'country':
      $data = get_countryCode_by_geoip();
      $query->where[2]['conditions'][1]['value'] = [$data];
      break;
  }
}

/**
 * {@inheritdoc}
 */
function get_countryCode_by_geoip() {
  $visitorIp = \Drupal::request()->getClientIp();
  if ($visitorIp === '127.0.0.1') {
    //$visitorIp = '62.240.224.0';  //FR
    $visitorIp = '14.140.162.242'; //IN
  }
  return \Drupal::service('geoip.geolocation')->geolocate($visitorIp)->getCountryCode();
}
